apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k-shui-dev

resources:
  - ../../base

labels:
  - pairs:
      app.kubernetes.io/instance: dev

configMapGenerator:
  - name: k-shui-config
    behavior: replace
    files:
      - config.yaml=k-shui.yaml

patches:
  - path: deployment-patch.yaml

images:
  - name: ghcr.io/k-shui/k-shui
    newTag: dev
