apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k-shui.fullname" . }}-config
  labels:
    {{- include "k-shui.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
