apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k-shui
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - secretName: k-shui-tls
      hosts:
        - k-shui.example.com
  rules:
    - host: k-shui.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: k-shui
                port:
                  number: 8090
